<?php

namespace Database\Seeders;

class DestinationData
{
    public static function getDestinations()
    {
        return [
            'vinh-ha-long' => [
                'name' => 'Vịnh Hạ Long',
                'slug' => 'vinh-ha-long',
                'description' => 'Một kỳ quan thiên nhiên thế giới với hàng ngàn hòn đảo đá vôi lớn nhỏ nổi bật trên mặt biển xanh ngắt.',
                'image' => 'https://w0.peakpx.com/wallpaper/150/598/HD-wallpaper-ha-long-bay-summer-travel-beautiful-nature-paradise-vietnam-asia-v%E1%BB%8Bnh-h%E1%BA%A1-long.jpg',
                'is_active' => true,
                'images' => [
                    'https://w0.peakpx.com/wallpaper/150/598/HD-wallpaper-ha-long-bay-summer-travel-beautiful-nature-paradise-vietnam-asia-v%E1%BB%8Bnh-h%E1%BA%A1-long.jpg',
                    'https://media.istockphoto.com/id/1201281530/photo/landscape-with-halong-bay.jpg?s=612x612&w=0&k=20&c=Kg4BgIyfMr5Egq-yaQNtBLjHP2U_db9WaLB0-4MGrb0=',
                    'https://w0.peakpx.com/wallpaper/767/409/HD-wallpaper-ha-long-bay-sea-beautiful-nature-paradise-vietnam-asia-v%E1%BB%8Bnh-h%E1%BA%A1-long-r-summer-travel.jpg',
                    'https://media.istockphoto.com/id/1182620587/photo/panoramic-view-of-ha-long-bay-vietnam.jpg?s=612x612&w=0&k=20&c=ieODoFfkiPPHeSYvWyAtfYwMdb0heNpgiHrtEKClAFE=',
                    'https://w0.peakpx.com/wallpaper/353/92/HD-wallpaper-halong-bay-ocean-summer-vietnam-cliffs-asia.jpg',
                    'https://media.istockphoto.com/id/690609980/photo/floating-village-rock-island-halong-bay-vietnam.jpg?s=612x612&w=0&k=20&c=TVLH1IBUEmS-RzkPVcQ77JkwWNx1EZG03UNUAxnyrgQ=',
                    'https://w0.peakpx.com/wallpaper/85/62/HD-wallpaper-boat-bay-vietnam-seascape-h%E1%BA%A1-long-bay.jpg',
                    'https://media.istockphoto.com/id/537641505/photo/halong-bay-vietnam.jpg?s=612x612&w=0&k=20&c=SZWI8yhpUiqy4NJI__dRKn80XJD-lhs_zsR4swJishU=',
                    'https://t3.ftcdn.net/jpg/07/69/26/42/360_F_769264251_eV9iUcgXW5Guzrhj4Nhs7fiF9PjEY2wi.jpg',
                    'https://media.istockphoto.com/id/1153561755/photo/beautiful-landscape-halong-bay-view-from-adove-the-bo-hon-island-halong-bay-vietnam.jpg?s=612x612&w=0&k=20&c=zd66GlpT2el8MTrWHWRUB48pzKPcR8naqqIjRbPtUEA=',
                    'https://media.tacdn.com/media/attractions-splice-spp-674x446/12/37/85/e6.jpg',
                    'http://www.halongbaycruise.vn/halongbay-images/news/img1/TWBG6O2181_Paradise-Elegance-halongbay.jpg',
                    'https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/15/26/30/d9.jpg',
                    'https://www.mrlinhadventure.com/UserFiles/image/Photo-2024/Ha-long-bay/Paradise-Elegance-5-star.jpg',
                    'https://www.shutterstock.com/image-photo/sung-sot-cave-halong-bay-260nw-2695120083.jpg',
                    'https://www.shutterstock.com/image-photo/sung-sot-cave-one-best-260nw-2654620739.jpg',
                ]
            ],
            'da-lat' => [
                'name' => 'Đà Lạt',
                'slug' => 'da-lat',
                'description' => 'Thành phố ngàn hoa với khí hậu mát mẻ quanh năm, nổi tiếng với những biệt thự cổ và rừng thông thơ mộng.',
                'image' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0b/92/11/0a/caption.jpg?w=900&h=500&s=1',
                'is_active' => true,
                'images' => [
                    'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0b/92/11/0a/caption.jpg?w=900&h=500&s=1',
                    'https://media.istockphoto.com/id/621486586/photo/beauty-da-lat-highland-homes-interspersed.jpg?s=612x612&w=0&k=20&c=cfdS3-Y5xwh5U-VU1MuDRWfODYNTv8A5AGdhaClTdz0=',
                    'https://www.vietnamonline.com/media/uploads/froala_editor/images/Dalat%20Flower%20Park.jpg',
                    'https://img.freepik.com/premium-photo/blossoming-beauty-stunning-apricot-cherry-blossoms-springtime-da-lat-city-vietnam_525043-5300.jpg',
                    'https://res.klook.com/image/upload/w_750,h_469,c_fill,q_85/w_80,x_15,y_15,g_south_west,l_Klook_water_br_trans_yhcmh3/activities/kzbxxh5igsbqun4qpp9w.jpg',
                    'https://travelsense.asia/wp-content/uploads/2014/12/dalat-vietnam.jpg',
                    'https://bcp.cdnchinhphu.vn/Uploaded_VGP/vuthuydung/20200901/dalat.jpg',
                    'https://image.vovworld.vn/w500/Uploaded/vovworld/ecfzyrrtlyr/2016_01_15/da%20lat%201.jpg',
                    'https://bcp.cdnchinhphu.vn/Uploaded_VGP/vuthuydung/20200901/dalathoa.jpg',
                    'https://thumbs.dreamstime.com/b/dalat-flower-garden-park-vietnam-march-da-lat-city-155441880.jpg',
                    'https://media.istockphoto.com/id/476395958/photo/flower-gardens-on-the-plateau-of-dalat.jpg?s=612x612&w=0&k=20&c=xJqBEhGo9cAggZrV4wu_JQ1hCjJqUzB6a9lbdgolY6o=',
                    'https://thumbs.dreamstime.com/b/dalat-vietnam-april-beautiful-scenery-famous-flower-park-april-dalat-vietnam-dalat-vietnam-april-beautiful-scenery-174939428.jpg',
                    'https://www.shutterstock.com/image-photo/beautiful-view-valley-love-dalat-260nw-1162814944.jpg',
                    'https://thumbs.dreamstime.com/b/scenic-tea-hill-misty-highlands-cau-dat-dalat-vietnam-green-plantations-beautiful-valley-mountain-range-agriculture-natural-387350878.jpg',
                    'https://vpt-en.b-cdn.net/wp-content/uploads/d/16/da-lat-vietnam.jpg.webp',
                    'https://www.vietnamdrive.com/wp-content/uploads/2022/09/xuan-huong-lake-in-sunset.jpg',
                    'https://lilystravelagency.com/wp-content/uploads/2024/11/image4-2.png',
                    'https://lilystravelagency.com/wp-content/uploads/2024/11/image12-1.png',
                    'https://www.shutterstock.com/image-photo/sunrise-xuan-huong-lake-dalat-260nw-1387206848.jpg',
                    'http://cdn1.vietnamtourism.org.vn//images/tour/hoacamtucau_jpg.jpg',
                    'https://www.dalattrip.com/media/2019/03/Many-young-people-come-to-check-in.jpg',
                    'https://img.freepik.com/premium-photo/da-lat-vietnam-1-november-2022-golden-bridge-with-hands-hydrangea-flowers-field-da-lat_200722-2581.jpg',
                    'https://lilystravelagency.com/wp-content/uploads/2024/12/dalat-garden2.png',
                    'https://dalat.tours/wp-content/uploads/2019/06/Fresh-Garden-Dalat.jpg',
                    'https://www.rustycompass.com/uploads/gallery/dalat-architecture-gallery-b-1012-1_13860631677.jpg',
                    'https://authentiktravel.com/media/blog/french-village-dalat-le-loi-street.jpg',
                    'https://media-cdn.tripadvisor.com/media/photo-s/29/c8/85/fe/mercure-danang-french.jpg',
                    'https://authentiktravel.com/media/blog/what%20to%20do%20in%20Da%20Lat%20in%202%20ou%203%20days%20travel%20blog.jpg',
                ]
            ],
            'hoi-an' => [
                'name' => 'Hội An',
                'slug' => 'hoi-an',
                'description' => 'Phố cổ yên bình với những ngôi nhà vàng nghệ, đèn lồng rực rỡ và dòng sông Hoài thơ mộng.',
                'image' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/1a/5c/2c/streets-by-riverfront.jpg?w=900&h=500&s=1',
                'is_active' => true,
                'images' => [
                    'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/1a/5c/2c/streets-by-riverfront.jpg?w=900&h=500&s=1',
                    'https://media.istockphoto.com/id/2160702210/photo/view-of-the-street-in-hoi-an-ancient-town-in-vietnam.jpg?s=612x612&w=0&k=20&c=C_i4M1zFahoZ7gyGX3v5SxqTjVGd7HapCtlvc4Eg7rk=',
                    'https://statics.vinpearl.com/hoi-an-lantern-2_1676896170.jpg',
                    'https://lookaside.instagram.com/seo/google_widget/crawler/?media_id=3345117314273302431',
                    'https://www.shutterstock.com/image-photo/hoi-an-vietnam-march-282018-260nw-1060195760.jpg',
                    'https://img.freepik.com/premium-photo/selective-focus-colourful-lanterns-street-hoi-ancient-town-vietnam_109442-33.jpg',
                    'https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/10/5f/27/ff.jpg',
                    'https://img.freepik.com/premium-photo/hoi-ancient-town-vietnam-with-lantern-texture-fabric-c-illustration-trending-background-decor_1020495-202608.jpg',
                    'https://www.shutterstock.com/image-photo/streets-traditional-ancient-yellow-houses-260nw-2525083987.jpg',
                    'https://images.travelandleisureasia.com/wp-content/uploads/sites/6/2025/10/30142650/Hoi-An-6.jpg?tr=w-480,f-jpg,pr-true',

                ]
            ],
            'nha-trang' => [
                'name' => 'Nha Trang',
                'slug' => 'nha-trang',
                'description' => 'Thành phố biển sôi động với bãi cát trắng mịn, nước biển trong xanh và tháp Trầm Hương biểu tượng.',
                'image' => 'https://lillagreen.com/wp-content/uploads/2025/08/Nha-Trang-46-585x439.jpg',
                'is_active' => true,
                'images' => [
                    'https://lillagreen.com/wp-content/uploads/2025/08/Nha-Trang-46-585x439.jpg',
                    'https://www.inparkmagazine.com/wp-content/uploads/2022/09/2022-HR-Vinpearl-VinWonders-Nha-Trang-Vietnam-9-696x431.jpg',
                    'https://media.istockphoto.com/id/2215325056/photo/russian-tourist-in-blue-dress-enjoying-vietnam-beach-vacation-aerial-view-from-pier-showing.jpg?s=612x612&w=0&k=20&c=edCnrUlcI0hNISBFgH9b9AO5a3OrJUhAV5jVoOS7J8w=',
                    'https://i.ytimg.com/vi/HjsREm0B26w/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLA1QU0RM_UBp3Kd5mEGuDwSQsmWXg',
                    'https://media.istockphoto.com/id/182839282/photo/aerial-shot-of-nha-trang-beach-in-vietnam.jpg?s=612x612&w=is&k=20&c=QwKmwM3juG-Gf_jtuMEk-EwcBFZnc9WkNZbcBzR8iVM=',
                    'https://i.ytimg.com/vi/T4IcTq9YQ8Y/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLAPuMHaHrOKLizeFDG4cUrJI8_w8w',
                    'https://www.shutterstock.com/image-photo/nha-trang-city-photo-trip-260nw-1461523439.jpg',
                    'https://www.asiatoptravel.com/images/image/Nha-Trang-Travel/Nha-Trang-Beach-1.jpg',
                    'https://www.iroamly.com/images/article/vietnam/nha-trang-beach.png',
                    'https://www.shutterstock.com/image-photo/po-nagar-cham-towers-nha-260nw-2666826219.jpg',
                    'https://authentiktravel.com/media/ckeditor/po%20nagar%20cham%20towers%20nha%20trang%20aerial%20view.jpg',
                    'https://www.shutterstock.com/image-photo/ponagar-thap-ba-po-nagar-600nw-2623047315.jpg',
                    'https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/12/27/0b/a9.jpg',
                    'https://www.shutterstock.com/image-photo/ponagar-tower-nha-trang-vietnam-260nw-2310624427.jpg',
                    'https://www.pelago.com/img/products/VN-Vietnam/hon-tam-island-mud-bath-experience-at-merperle-hon-tam-resort-optional-vinwonders-nha-trang-ticket-nha-trang/c5ea0c98-26b7-45fc-815d-a7bbeb5a6650_hon-tam-island-mud-bath-experience-at-merperle-hon-tam-resort-optional-vinwonders-nha-trang-ticket-nha-trang-medium.jpg',
                    'https://www.svietnamtravel.com/image/cache/catalog/tour-img/Nha-Trang-11-800x450.jpg',
                    'http://ttgasia.2017.ttgasia.com/wp-content/uploads/sites/2/2021/09/Sanya-shutterstock_1431737486.jpg',
                    'https://i.ytimg.com/vi/T4IcTq9YQ8Y/hqdefault.jpg',
                    'https://www.shutterstock.com/image-photo/beautiful-bai-tam-hon-chong-260nw-2533269001.jpg',
                    'https://i.ytimg.com/vi/T4IcTq9YQ8Y/sddefault.jpg',
                    'https://www.travelauthenticasia.com/photos/tours/vietnam/gallery/nhatrang/nhatrang_17.jpg',
                    'https://assets.dm.rccl.com/is/image/RoyalCaribbeanCruises/royal/data/ports/nha-trang-vietnam/overview/nha-trang-vietnam-fishing-boats.jpg?$750x320$',
                ]
            ],
            'sapa' => [
                'name' => 'Sapa',
                'slug' => 'sapa',
                'description' => 'Thị trấn trong sương với ruộng bậc thang hùng vĩ, đỉnh Fansipan nóc nhà Đông Dương và văn hóa bản địa độc đáo.',
                'image' => 'https://thumbs.dreamstime.com/b/beautiful-rice-terrace-field-sa-pa-fansipan-mountain-peak-travel-destination-hoang-lien-son-range-lao-highest-178361610.jpg',
                'is_active' => true,
                'images' => [
                    'https://thumbs.dreamstime.com/b/beautiful-rice-terrace-field-sa-pa-fansipan-mountain-peak-travel-destination-hoang-lien-son-range-lao-highest-178361610.jpg',
                    'https://sapatoursfromhanoi.com/wp-content/uploads/2016/10/Sapa-Terraced-rice-fields.webp',
                    'http://www.sapa-tour.net/wp-content/uploads/2014/08/Sapa-Rice-Terrace.jpg',
                    'https://media.istockphoto.com/id/1430371073/photo/aerial-view-of-golden-rice-terraces-at-mu-cang-chai-town-near-sapa-city-north-of-vietnam.jpg?s=612x612&w=0&k=20&c=bOSoIPrIEuM0RiSzazYUYgr5N4OK3thhKG9nLntO72o=',
                    'https://thumbs.dreamstime.com/b/beautiful-rice-terrace-field-sa-pa-fansipan-mountain-peak-travel-destination-hoang-lien-son-range-lao-highest-178368722.jpg',
                    'https://izitour.com/media/blog/sapa-rice-field.webp',
                    'https://www.shutterstock.com/image-photo/aerial-view-golden-rice-terraces-260nw-2696753405.jpg',
                    'https://www.shutterstock.com/image-photo/aerial-view-golden-rice-terraces-260nw-2696753471.jpg',
                    'https://as1.ftcdn.net/v2/jpg/03/08/47/94/1000_F_308479436_f7oH1ssJPwogl2dtLdLuFqOo5Y6RJQ4p.jpg',
                    'https://www.shutterstock.com/image-photo/aerial-view-golden-rice-terraces-260nw-2696753685.jpg',
                    'https://izitour.com/media/ckeditor/vetta-fansipan-tetto-d-indocina.webp',
                    'https://izitour.com/media/blog/sapa-glass-bridge.webp',
                    'https://izitour.com/media/blog/sapa-fansipan-mountain-vietnam.webp',
                    'https://statics.vinpearl.com/cat-cat-village-01_1682416950.jpg',
                    'https://autourasia.com/uploads/Travel-Guide-Vietnam/Sapa/best-things-to-do-Cat-Cat-Village/900-banner-Cat-Cat-Village.jpg',
                    'https://thebackpackingfamily.com/wp-content/uploads/2023/01/IMG_2982.jpg',
                    'https://lirp.cdn-website.com/82dc0a8d/dms3rep/multi/opt/cat-cat-village-in-sapa_15c65-640w.webp',
                    'https://thumbs.dreamstime.com/b/aerial-view-fansipan-mountain-hills-valley-summer-paddy-rice-terraces-green-agricultural-fields-rural-area-aerial-161146053.jpg',
                    'https://media.gettyimages.com/id/1181241656/photo/aerial-top-view-of-fansipan-mountains-with-paddy-rice-terraces-green-agricultural-fields-in.jpg?s=1024x1024&w=gi&k=20&c=UragUqH8zelHzq6ISIxmzddDsx8ePeAQm4j0iOyibP4=',
                    'https://thumbs.dreamstime.com/b/aerial-view-fansipan-mountain-hills-valley-summer-paddy-rice-terraces-green-agricultural-fields-rural-area-aerial-161145652.jpg',
                    'https://www.shutterstock.com/image-photo/beautiful-panorama-top-view-growing-260nw-1238014930.jpg',
                    'https://thumbs.dreamstime.com/b/aerial-view-fansipan-mountain-hills-valley-summer-paddy-rice-terraces-green-agricultural-fields-rural-area-aerial-161145563.jpg',
                    'https://www.shutterstock.com/shutterstock/videos/1039439978/thumb/1.jpg?ip=x480',
                    'https://thumbs.dreamstime.com/b/aerial-top-view-fansipan-mountains-paddy-rice-terraces-green-agricultural-fields-countryside-rural-area-hills-valley-161187126.jpg',
                    'https://media.istockphoto.com/id/1179825795/photo/fansipan-mountain-hills-valley-on-summer-with-paddy-rice-terraces-green-agricultural-fields.jpg?s=612x612&w=is&k=20&c=OD1gMO0m1ccXAQdNkVQ7uKRQ0qs4THLxC7a3G4wAC8s=',
                    'https://thumbs.dreamstime.com/b/fansipan-mountains-paddy-rice-terraces-sapa-vietnam-fields-prepare-harvest-northwest-landscapes-162710656.jpg',
                ]
            ],
            'phu-quoc' => [
                'name' => 'Phú Quốc',
                'slug' => 'phu-quoc',
                'description' => 'Đảo Ngọc thiên đường với những resort sang trọng, bãi Sao tuyệt đẹp và cáp treo vượt biển dài nhất thế giới.',
                'image' => 'https://static.vecteezy.com/system/resources/thumbnails/044/846/213/large/beautiful-tropical-beach-and-sea-landscape-at-sunset-paradise-beaches-of-fukuoka-phu-quoc-sonasea-beach-palm-trees-sea-sunset-indian-ocean-luxury-beauty-of-nature-rest-relaxation-video.jpg',
                'is_active' => true,
                'images' => [
                    'https://static.vecteezy.com/system/resources/thumbnails/044/846/213/large/beautiful-tropical-beach-and-sea-landscape-at-sunset-paradise-beaches-of-fukuoka-phu-quoc-sonasea-beach-palm-trees-sea-sunset-indian-ocean-luxury-beauty-of-nature-rest-relaxation-video.jpg',
                    'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/19/f7/45/sunset-beach-resort-spa.jpg?w=900&h=500&s=1',
                    'https://static.vecteezy.com/system/resources/thumbnails/044/292/842/small_2x/paradise-beaches-of-fukuoka-phu-quoc-sonasea-beach-palm-trees-sea-sunset-indian-ocean-luxury-vacation-near-hotels-travel-travel-agency-destination-beauty-of-nature-rest-relaxation-video.jpg',
                    'https://www.shutterstock.com/image-photo/sunset-long-beach-phu-quoc-260nw-390296839.jpg',
                    'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/19/f4/56/b2/vida-loca-resort-sunset.jpg?w=900&h=-1&s=1',
                    'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0f/36/0b/9e/beach-sunset.jpg?w=900&h=500&s=1',
                    'https://thumbs.dreamstime.com/b/sunset-starfish-beach-phu-quoc-beautiful-sunny-landscape-taken-paradise-rach-vem-hot-day-island-vietnam-ganh-dau-cape-187753920.jpg',
                    'https://pix10.agoda.net/hotelImages/9612717/-1/004a10c201a2530d378d52f6d337e1c4.jpg?ca=10&ce=1&s=414x232',
                    'https://q-xx.bstatic.com/xdata/images/hotel/max500/666994337.jpg?k=c92ef3210edce69b36aee09ed0075cce1d6457856d74b83c64b023662502316f&o=',
                    'https://pix10.agoda.net/hotelImages/9612717/-1/40a120eea8b51421845cb37b572d44ac.jpg?ca=10&ce=1&s=414x232',
                    'https://media.odynovotours.com/article/75000/phu-quoc-travel-map_74409.jpg',
                    'https://www.shutterstock.com/image-photo/phu-quoc-vietnam-january-31-600nw-2673155349.jpg',
                    'https://www.chensea-resort.com/wp-content/uploads/2025/06/sao-beach.jpg',
                    'https://www.shutterstock.com/image-photo/phu-quoc-vietnam-january-31-260nw-2673155349.jpg',
                    'https://photo620x400.mnstatic.com/02a4bc6d687c51e85942647069a788ed/sao-beach-in-phu-quoc-island.jpg',
                    'https://www.shutterstock.com/image-photo/beautiful-white-sand-bai-sao-600nw-1781476943.jpg',
                    'https://salindaresort.com/uploads/articles/102/cap-treo-phu-quoc-ve-gia-va-dich-vu-nam-2024.jpg',
                    'https://visitphuquoc.com.vn/VisitPhuQuoc/Post/XEM%20G%C3%8C%20L%C3%80M%20G%C3%8C/Gi%E1%BA%A3i%20tr%C3%AD%20-%20Th%C6%B0%20gi%C3%A3n/1842/image-thumb__1842__720_jpg/phu-quoc.7eb7c289.jpg',
                    'https://media.tacdn.com/media/attractions-splice-spp-674x446/11/5c/f2/66.jpg',
                    'https://www.shutterstock.com/image-photo/aerial-view-cable-car-gondola-260nw-2623059977.jpg',
                    'https://d2mgzmtdeipcjp.cloudfront.net/files/magazine/2025/02/02/17384860292606.jpg',
                    'https://www.shutterstock.com/editorial/image-editorial/MbT8UazdOdDeY812MDE1NDg=/gondoliers-row-tourists-through-venice-canal-grand-440nw-15236843d.jpg',
                    'https://www.shutterstock.com/editorial/image-editorial/MfT6U1zfOcD2Yd1eMDE1NDg=/gondoliers-row-tourists-through-venice-canal-grand-440nw-15236843e.jpg',
                    'https://rootytrip.com/wp-content/uploads/2023/02/grand-world-phu-quoc-18.jpg',
                    'https://media-cdn.tripadvisor.com/media/photo-s/1b/19/f7/45/sunset-beach-resort-spa.jpg',
                    'https://q-xx.bstatic.com/xdata/images/hotel/max500/490190291.jpg?k=b8347af56ef3000b0ef60508d7c50a2738ae41a9e0f487df6c7eae65c30d747c&o=',
                    'https://pix10.agoda.net/hotelImages/9612717/-1/a07ea3bfbe28e913a55406dbfb598c3c.jpg?ca=10&ce=1&s=414x232',
                ]
            ],
            'long-xuyen' => [
                'name' => 'Long Xuyên',
                'slug' => 'long-xuyen',
                'description' => 'Thành phố yên bình bên dòng sông Hậu, nổi tiếng với chợ nổi Long Xuyên đậm chất miền Tây sông nước.',
                'image' => 'https://thanhnien.mediacdn.vn/thumb_w/750/325084952045817856/2024/11/20/base64-17320785680081495701555.jpeg',
                'is_active' => true,
                'images' => [
                    'https://thanhnien.mediacdn.vn/thumb_w/750/325084952045817856/2024/11/20/base64-17320785680081495701555.jpeg',
                    'https://i.ytimg.com/vi/oiBE9KXsztg/sddefault.jpg',
                    'https://lookaside.fbsbx.com/lookaside/crawler/media/?media_id=1964493993758353',
                    'https://i.ytimg.com/vi/S6c63eyLiaM/hqdefault.jpg?sqp=-oaymwEmCOADEOgC8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGCYgXShyMA8=&rs=AOn4CLAzsiqAlvN6JIS22LfDvjuPpm_tsQ',
                    'https://bizweb.dktcdn.net/100/568/826/files/an-giang-mua-pin-o-dau.jpg?v=1759642606857',
                    'https://i.ytimg.com/vi/oiBE9KXsztg/hqdefault.jpg',
                    'https://izitour.com/media/ckeditor/cho-noi-floating-market.webp',
                    'https://www.handspan.com/uploads/7%20MEKONG%20DELTA/620_x_400/Long-Xuyen-floating-market_5.jpg',
                    'https://izitour.com/media/blog/long-xuyen-floating-market-vietnam.webp',
                    'https://i.ex-cdn.com/theinvestor.vn/files/content/2022/05/07/cho-noi-cai-rang-3-1955.jpg',
                    'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Camau0205.jpg/500px-Camau0205.jpg',
                    'https://upload.wikimedia.org/wikipedia/commons/5/57/Keir_Starmer_meets_T%C3%B4_L%C3%A2m_29-10-2025_%286%29_%28cropped%29.jpg',
                    'https://image.vietnamnews.vn/uploadvnnews/Article/2024/1/7/325187_pnp%20tuong%20dai.jpg',
                    'https://image.vietnamnews.vn/uploadvnnews/Article/2025/10/13/456740_5296165743971809_vna_potal_dai_tuong_bo_truong_quoc_phong_phan_van_giang_tiep_chu_tich_co_quan_cong_nghiep_quoc_phong_tho_nhi_ky_8336554.jpg',
                    'https://image.vietnamnews.vn/uploadvnnews/Article/2024/12/30/397294_5048237426490980_vna_potal_thanh_pho_ho_chi_minh_thong_xe_dua_vao_khai_thac_4_cong_trinh_giao_thong__7782060.jpg',
                    'https://img.freepik.com/premium-photo/chau-doc-city-giang-province-viet-nam-aerial-view-this-is-city-bordering-cambodia_706532-458.jpg',
                    'https://www.planetware.com/img/gallery/vietnams-top-11-tourist-attractions-to-check-out-on-your-first-trip/intro-1758714525.jpg',
                    'https://lookaside.fbsbx.com/lookaside/crawler/media/?media_id=4887324911294418',
                    'https://i.ytimg.com/vi/D62XEVobsng/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBwj8zMBAdkFfmga6OuYy2IGNGVcA',
                    'https://lookaside.fbsbx.com/lookaside/crawler/media/?media_id=2313799655648234',
                    'https://i.ytimg.com/vi/mqYJlunb7zc/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBmynAOknbGMYICdklev6MGn2IQ3Q',
                    'https://bizweb.dktcdn.net/thumb/grande/100/568/826/articles/an-giang-mua-pin-o-dau.jpg?v=1759642621200',
                    'https://i.ytimg.com/vi/4Y4Co0daHPI/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLAeAAWpbogZB329zyQnCwLV7MhM0Q',
                    'https://www.tiktok.com/api/img/?itemId=7440815946878438674&location=0&aid=1988',
                    'https://file.hstatic.net/200000836389/file/an-giang-co-gi-choi__11__7d244a5e1bfc4ed78bb50069cb7dfca6.jpg',
                    'https://baoquangbinh.vn/dataimages/202111/original/images720713_M_i_Vi_t___L____c_Th_nh.jpg',
                ]
            ],
            'hue' => [
                'name' => 'Cố đô Huế',
                'slug' => 'hue',
                'description' => 'Di sản văn hóa thế giới với Kinh thành Huế cổ kính, lăng tẩm vua chúa uy nghiêm và nhã nhạc cung đình.',
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Hu%E1%BA%BF_%282024%29_-_Meridian_Gate_-_Ng%E1%BB%8D_M%C3%B4n_%28Ho%C3%A0ng_th%C3%A0nh_Hu%E1%BA%BF%29_-_img_02.jpg/500px-Hu%E1%BA%BF_%282024%29_-_Meridian_Gate_-_Ng%E1%BB%8D_M%C3%B4n_%28Ho%C3%A0ng_th%C3%A0nh_Hu%E1%BA%BF%29_-_img_02.jpg',
                'is_active' => true,
                'images' => [
                    'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Hu%E1%BA%BF_%282024%29_-_Meridian_Gate_-_Ng%E1%BB%8D_M%C3%B4n_%28Ho%C3%A0ng_th%C3%A0nh_Hu%E1%BA%BF%29_-_img_02.jpg/500px-Hu%E1%BA%BF_%282024%29_-_Meridian_Gate_-_Ng%E1%BB%8D_M%C3%B4n_%28Ho%C3%A0ng_th%C3%A0nh_Hu%E1%BA%BF%29_-_img_02.jpg',
                    'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/11/7a/57/7b/vue-interieure.jpg?w=900&h=-1&s=1',
                    'https://www.handspan.com/uploads/VBLOG/620x400blogcontent/Hue-Imperial-City-from-outside.jpg',
                    'https://www.shutterstock.com/image-photo/ancient-architecture-hue-imperial-city-260nw-2668044223.jpg',
                    'https://www.historyhit.com/app/uploads/2020/11/Imperial-City-of-Hue.jpg',
                    'https://www.handspan.com/uploads/VBLOG/620x400blogcontent/Ngo-Mon-Gate.jpg',
                    'https://www.pelago.com/img/products/VN-Vietnam/a-full-day-hue-citadel-tour-from-danang/e413d281-298b-4de1-a9ea-fcd14c73a18a_a-full-day-hue-citadel-tour-from-danang.jpg',
                    'https://autourasia.com/uploads/Travel-Guide-Vietnam/Hue/Hue-Imperial-Citadel/700x467-Hue-Imperial-Citadel-3.jpg',
                    'https://afuncouple.com/wp-content/uploads/2022/10/Best-things-to-see-in-Hue_Vietnam-16.jpg',
                    'https://www.pelago.com/img/products/VN-Vietnam/a-full-day-hue-citadel-tour-from-danang/e413d281-298b-4de1-a9ea-fcd14c73a18a_a-full-day-hue-citadel-tour-from-danang-medium.jpg',
                    'https://izitour.com/media/blog/mausoleum-of-emperor-khai-dinh.webp',
                    'https://www.discoverimages.com/p/251/tomb-khai-dinh-lang-khai-dinh-19445183.jpg.webp',
                    'https://www.mediastorehouse.com.au/p/251/tomb-khai-dinh-lang-khai-dinh-19445183.jpg.webp',
                    'https://www.shutterstock.com/image-photo/aerial-view-beautiful-royal-tomb-260nw-2157423935.jpg',
                    'https://www.shutterstock.com/image-photo/thien-mu-pagoda-one-ancient-260nw-2199772385.jpg',
                    'https://phongnhalocals.com/wp-content/uploads/2020/10/Perfume-River-Sunset-Cruise-Phong-Nha-Locals-4.jpg',
                    'https://media-cdn.tripadvisor.com/media/photo-s/09/9b/d8/ca/thien-mu-pagoda.jpg',
                    'https://res.klook.com/image/upload/w_750,h_469,c_fill,q_85/w_80,x_15,y_15,g_south_west,l_Klook_water_br_trans_yhcmh3/activities/p4fj1x8pc3dhy6dko8y1.jpg',
                    'https://i0.wp.com/offbeatexplorers.com/wp-content/uploads/2019/06/The-Imperial-city-of-Hue-Vietnam-Hue-Citadel-at-night.jpg?resize=730%2C410&ssl=1',
                    'https://media.gettyimages.com/id/1453885501/photo/sunset-meridian-gate-imperial-palace-hue-vietnam-historic-royal-palace-set-within-the.jpg?s=612x612&w=gi&k=20&c=UhblYUU2LJHlQQz07FPby4nymCAn1WIRgTyMHKwqQhQ=',
                    'https://www.shutterstock.com/image-photo/ancient-architecture-hue-imperial-city-260nw-2668044309.jpg',
                    'https://thumbs.dreamstime.com/b/hue-vietnam-imperial-citadel-view-palace-corridor-red-door-window-shutters-old-wooden-passageway-traditional-274656157.jpg',
                    'https://www.shutterstock.com/image-photo/ancient-architecture-hue-imperial-city-260nw-2668044387.jpg',
                    'https://thehappyjetlagger.com/wp-content/uploads/2015/06/hue-zitadelle-09-1-770x513.jpg',
                    'https://havecamerawilltravel.photography/wp-content/uploads/2016/11/hue-imperial-city-hue-vietnam-ngo-mon-gate-and-bridge-66-copyright-havecamerawilltravel-com-800x450.jpg',
                    'https://www.shutterstock.com/image-photo/ancient-architecture-hue-imperial-city-260nw-2668044353.jpg',
                    'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/11/7a/57/7b/vue-interieure.jpg?w=500&h=500&s=1',
                    'https://www.shutterstock.com/image-photo/imperial-city-hue-vietnam-ancient-260nw-2684997917.jpg',
                ]
            ],
            'da-nang' => [
                'name' => 'Đà Nẵng',
                'slug' => 'da-nang',
                'description' => 'Thành phố đáng sống nhất Việt Nam với Cầu Vàng, Cầu Rồng phun lửa và những bãi biển đẹp mê hồn.',
                'image' => 'https://media.tacdn.com/media/attractions-splice-spp-674x446/12/71/47/6a.jpg',
                'is_active' => true,
                'images' => [
                    'https://media.tacdn.com/media/attractions-splice-spp-674x446/12/71/47/6a.jpg',
                    'https://images.squarespace-cdn.com/content/v1/63a21625334f121dff7a59c1/716715f9-a004-4e7c-bd09-8544ff933990/_DSC7675.jpg',
                    'https://media.tacdn.com/media/attractions-splice-spp-674x446/07/20/ad/6e.jpg',
                    'https://statics.vinpearl.com/dragon-bridge-1_1664459719.jpeg',
                    'https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/12/44/50/e7.jpg',
                    'https://media.tacdn.com/media/attractions-splice-spp-674x446/07/94/66/7d.jpg',
                    'https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/10/12/50/3c.jpg',
                    'https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/09/2c/08/7f.jpg',
                    'https://images.squarespace-cdn.com/content/v1/63a21625334f121dff7a59c1/716715f9-a004-4e7c-bd09-8544ff933990/_DSC7675.jpg',
                    'https://jackytravel.com/wp-content/uploads/2024/12/Danang-Dragon-Bridge-3.jpg',
                    'https://images.squarespace-cdn.com/content/v1/63a21625334f121dff7a59c1/b2f1ca32-fdca-47ed-b86e-935cf61e792d/_DSC7678.jpg',
                    'https://vietnamlife.asia/wp-content/uploads/2025/01/My-Khe-Beach-in-Da-Nang.jpg',
                    'https://www.shutterstock.com/image-photo/my-khe-beach-beautiful-danang-260nw-2356316985.jpg',
                    'https://img.freepik.com/premium-photo/white-cloud-blue-sky-with-sea-beach-hau-hin-thailand_33523-48.jpg',
                    'https://www.shutterstock.com/image-photo/da-nang-vietnam-september-12th-260nw-1505838104.jpg',
                    'https://img.freepik.com/premium-photo/my-khe-city-beach-danang_78361-10345.jpg',
                    'https://media.tacdn.com/media/attractions-splice-spp-674x446/11/ac/a9/a5.jpg',
                    'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/f2/a9/d6/20200219-211234-largejpg.jpg?w=900&h=500&s=1',
                    'https://media.tacdn.com/media/attractions-splice-spp-674x446/15/73/df/99.jpg',
                    'https://vietnamtour.in/wp-content/uploads/Dragon-Bridge-in-Da-Nang-1-1.jpg-1.jpg',
                    'https://media.tacdn.com/media/attractions-splice-spp-674x446/12/4e/c5/50.jpg',
                    'https://media.istockphoto.com/id/1567573349/photo/dragon-bridge-at-twilight-in-da-nang-vietnam.jpg?s=612x612&w=0&k=20&c=LhS16JWNf_QiYzM9aGf_3PVNMFzzIoiqOp6FZ7tKxYU=',
                    'https://media.tacdn.com/media/attractions-splice-spp-674x446/0a/0e/37/ba.jpg',
                    'https://media.istockphoto.com/id/1487232675/vector/world-famous-landmark-great-chinese-wall-and-golden-bridge-in-da-nang-beautiful-landscape.jpg?s=612x612&w=0&k=20&c=uOsJ3THPZA9EC4Ifgp6SkwU92-f8_PSZqsOE5iSF00A=',
                    'https://media.tacdn.com/media/attractions-splice-spp-674x446/13/e6/a0/4e.jpg',
                    'https://www.shutterstock.com/image-illustration/watercolor-style-digital-art-da-600nw-2228006935.jpg',
                    'https://i.ytimg.com/vi/TR-GfP5v55A/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLC2LGPKPn_bU32C499MnY1Mecem1g',
                ]
            ],
        ];
    }

    public static function getDefaultImages()
    {
        return [
            'https://vietnam.travel/sites/default/files/styles/top_banner/public/2017-06/ha-long-bay-vietnam-travel-5.jpg',
            'https://vcdn1-dulich.vnecdn.net/2022/01/25/mua-vang-tam-coc-1643083487.jpg'
        ];
    }
}
