<?php

namespace Database\Factories;

use App\Models\Booking;
use App\Models\Tour;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Booking>
 */
class BookingFactory extends Factory
{
    protected $model = Booking::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $adults = fake()->numberBetween(1, 4);
        $children = fake()->numberBetween(0, 2);
        $infants = fake()->numberBetween(0, 1);

        return [
            // 1. Define the relationship: Ensures a single User record is created or used.
            'user_id' => User::factory(),
            'tour_id' => Tour::factory(),

            // 2. Use attribute closures to fetch details (name, email) 
            // from the User record linked by 'user_id' after it has been resolved.
            // This ensures data consistency and avoids creating extra User records.
            'name' => fn (array $attributes) => User::find($attributes['user_id'])->name,
            'email' => fn (array $attributes) => User::find($attributes['user_id'])->email,
            'phone' => fake()->numerify('09########'),
            
            'adults' => $adults,
            'children' => $children,
            'infants' => $infants,
            'total_people' => $adults + $children + $infants,
            'special_requests' => fake()->boolean(30) ? fake()->sentence() : null,
            'status' => 'pending',
            // 'booking_code' => null, // Will be auto-generated by model
            'total_amount' => fake()->numberBetween(2000000, 10000000),
        ];
    }

    /**
     * Indicate that the booking is confirmed.
     */
    public function confirmed(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => 'confirmed',
        ]);
    }

    /**
     * Indicate that the booking is cancelled.
     */
    public function cancelled(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => 'cancelled',
        ]);
    }

    /**
     * Configure the factory to calculate total amount based on tour prices.
     */
    public function configure()
    {
        return $this->afterCreating(function (Booking $booking) {
            // This section is kept as is to calculate the total amount after creation.
            if ($booking->tour) {
                $total = ($booking->adults * $booking->tour->price_adult) +
                         ($booking->children * $booking->tour->price_child) +
                         ($booking->infants * $booking->tour->price_infant);
                $booking->update(['total_amount' => $total]);
            }
        });
    }
}